name = "awwbot"
main = "./src/server.js"
compatibility_date="2023-05-18"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

kv_namespaces = [
  { binding = "DEFAULTCODERBOT", id = "f3e9811f337941d4bf75b764f50d2b76" }
]